sentences = [
    r"你今天寫扣了嗎？",
    r"多多參加系上活動程設課會加分哦！",
    r"曾經有位學長寫了一個交作業網站，\n叫做郭老愛你。",
    r"郭老說過，零分很危險。",
    r"郭老說過，每週至少要花 87 小時練習寫程式。",
    r"根據大數據分析，\n每年至少有 1/3 的同學明年會再修一次程設課",
    r"給自由的狐狸一次機會owo\nhttps://www.mozilla.org/zh-TW/firefox/",
    r"https://www.getgnulinux.org/zh-tw/",
    r"<a href='https://zh.wikipedia.org/wiki/%E7%BC%96%E8%BE%91%E5%99%A8%E4%B9%8B%E6%88%98'>編輯器之戰</a>",
    r"Visual Studio Code 讚讚\nhttps://code.visualstudio.com",
    r"不要用 Windows 啦！",
    r"互相傷害啊。",
    r"天氣好的時候，天空是藍的。",
    r"在非洲，每 60 秒過去就過了 1 分鐘。",
    r"(ˊ・ω・ˋ)",
    r"(ˊ・ω・ˋ)(ˊ・ω・ˋ)",
    r"(ˊ・ω・ˋ)(ˊ・ω・ˋ)(ˊ・ω・ˋ)",
]
