sentences = [
    "你今天寫扣了嗎？",
    "多多參加系上活動程設課會加分哦！",
    "曾經有位學長寫了一個交作業網站，\n叫做郭老愛你。",
    "郭老說過，零分很危險。",
    "郭老說過，每週至少要花 87 小時練習寫程式。",
    "根據大數據分析，\n每年至少有 1/3 的同學明年會再修一次程設課",
    "給自由的狐狸一次機會owo\nhttps://www.mozilla.org/zh-TW/firefox/",
    "https://www.getgnulinux.org/zh-tw/",
    "<a href='https://zh.wikipedia.org/wiki/%E7%BC%96%E8%BE%91%E5%99%A8%E4%B9%8B%E6%88%98'>編輯器之戰</a>",
    "Visual Studio Code 讚讚\nhttps://code.visualstudio.com",
    "不要用 Windows 啦！",
    "互相傷害啊。",
    "天氣好的時候，天空是藍的。",
    "在非洲，每 60 秒過去就過了 1 分鐘。",
    "(ˊ・ω・ˋ)",
    "(ˊ・ω・ˋ)(ˊ・ω・ˋ)",
    "(ˊ・ω・ˋ)(ˊ・ω・ˋ)(ˊ・ω・ˋ)",
    "現在有網頁版本的 KCOJ 囉！\nhttps://kcoj.ntut.com.tw",
    "現在有網頁版本的 KCOJ 囉！\nhttps://kcoj.ntut.com.tw",
    "現在有網頁版本的 KCOJ 囉！\nhttps://kcoj.ntut.com.tw",
    "現在有網頁版本的 KCOJ 囉！\nhttps://kcoj.ntut.com.tw",
    "現在有網頁版本的 KCOJ 囉！\nhttps://kcoj.ntut.com.tw",
    "現在有網頁版本的 KCOJ 囉！\nhttps://kcoj.ntut.com.tw",
    "現在有網頁版本的 KCOJ 囉！\nhttps://kcoj.ntut.com.tw",
]
