sentences = ["你今天寫扣了嗎？",
             "多多參加系上活動程設課會加分哦！",
             "曾經有位學長寫了一個交作業網站，\n叫做郭老愛你。"
             "郭老說過，零分很危險。",
             "郭老說過，每週至少要花 87 小時練習寫程式。",
             "GNOME > KDE，我覺得啦。",
             "根據大數據分析，\n每年至少有 1/3 的同學會在明年程設課時見到郭老",
             "我偏好使用 POSIX 相容的作業系統做開發。",
             "你有用過 Windows 以外的作業系統嗎？",
             "如果你想入門 Linux 的世界，\n建議你從 Ubuntu 或 Fedora 開始。",
             "你知道 CLI 與 GUI 的差別與各自的優缺點嗎？",
             "bash 跟 cmd 各方面都是天與地之間的差別。",
             "信 VIM 教得永生！",
             "編輯器的話，我覺得 Visual Studio Code 很好用。\nhttps://code.visualstudio.com",
             "買一台 MacBook 是脫離 Windows 最懶人的方式。",
             "如果你對資訊有濃厚的興趣，\n學生計算機年會 SITCON 你絕對不能錯過。\n2018 籌備中 http://fb.me/SITCONtw",
             "北科程式設計研究社 NPC 歡迎各位資工大大一起來路過～\nhttp://fb.me/NPC.OwO/",
             "臺大開源社 NTUOSC 歡迎外校朋友們，一同參與開源盛事！\nhttp://fb.me/NTUOSC/",
             "<a href='http://fb.me/SITCONtw'>SITCON</a> Telegram 群組：\nhttps://t.me/SITCONgeneral",
             "來互相傷害啊。",
             "天氣好的時候，天空是藍的。",
             "在非洲，每 60 秒過去就過了 1 分鐘。",
             "(ˊ・ω・ˋ)",
             "(ˊ・ω・ˋ)(ˊ・ω・ˋ)",
             "(ˊ・ω・ˋ)(ˊ・ω・ˋ)(ˊ・ω・ˋ)"]